global_defs {
    router_id LB_${BASE_DOMAIN}
    enable_script_security
    script_user root
}

# Health check — is HAProxy alive?
vrrp_script chk_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval 2
    weight 2
}

# ── Internal HAProxy VIP ─────────────────────────────────────────────────────
vrrp_instance VI_HAPROXY {
    state MASTER
    interface ${NIC_NAME}
    virtual_router_id 193
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ChangeMe-Keepalived
    }
    virtual_ipaddress {
        ${IP_PREFIX}.193/22
    }
    track_script {
        chk_haproxy
    }
}

# ── Rancher Manager VIP ──────────────────────────────────────────────────────
vrrp_instance VI_RANCHER {
    state MASTER
    interface ${NIC_NAME}
    virtual_router_id 210
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ChangeMe-Keepalived
    }
    virtual_ipaddress {
        ${RANCHER_VIP}/22
    }
    track_script {
        chk_haproxy
    }
}

# ── Applications VIP ─────────────────────────────────────────────────────────
vrrp_instance VI_APPS {
    state MASTER
    interface ${NIC_NAME}
    virtual_router_id 230
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ChangeMe-Keepalived
    }
    virtual_ipaddress {
        ${APPS_VIP}/22
    }
    track_script {
        chk_haproxy
    }
}
