# Beryl AX / GL-MT3000 
host beryl-ax {
  option host-name "beryl-ax.homelab.kubernerdes.lab";
  hardware ethernet 9e:83:c4:4a:b8:c5;
  fixed-address 10.0.0.4;
}

#################################################
## Management Nodes
# NUC-i7-01 (intel NUC - i7 (dark color, newer))
host nuc-00 {
  option host-name "nuc-00.homelab.kubernerdes.lab";
  hardware ethernet 1c:69:7a:6b:a9:0d;
  fixed-address 10.0.0.10;
  #filename "efi/ubuntu-22.04.2/grubx64.efi";
}


host glkvm {
  option host-name "glkvm";
  hardware ethernet 94:83:c4:b1:ea:43;
  fixed-address 10.0.0.249;
}
  
host jarvis {
  option host-name "jarvis";
  hardware ethernet f0:2f:74:20:1f:51;
  fixed-address 10.0.0.250;
}
host spark-e {
  option host-name "spark-e";
  hardware ethernet 4c:bb:47:2b:e1:94;
  fixed-address 10.0.0.251;
}
host wheatley {
  option host-name "wheatley";
  #hardware ethernet 94:c6:91:1c:81:f6;
  hardware ethernet 00:50:b6:ab:35:23;
  fixed-address 10.0.0.252;
}
host blackmesa {
  option host-name "blackmesa";
  hardware ethernet a0:80:69:c6:99:18;
  fixed-address 10.0.0.253;
}
